import {randomUUID} from 'node:crypto';import {Pool} from 'pg';import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {LedgerKernel} from '../../packages/accounting/src/kernel.ts';import {canonicalJson} from '../../packages/domain/src/contracts.ts';
import {applyPostgresMigrations,getPostgresSchemaStatus} from '../../packages/accounting/src/migrations.ts';
import {encryptSecret} from '../../server/funding/vault.ts';import {createParticipationService,type ParticipationAgentContext,type ParticipationService} from '../../server/participation/service.ts';
import {createHypothesisSubmissionAdmissionService,createHypothesisSubmissionDeliveryService,
  createProjectResearchDeliveryPolicyService} from '../../server/research-memory/index.ts';
import {PINNED_REVIEWED_WRITEBACK_CONTRACT} from '../../server/research-memory/pinned-writeback-contract.ts';
const baseUrl=process.env.MOTIVE_TEST_DATABASE_URL,pgDescribe=baseUrl?describe:describe.skip;
const vaultKey=Buffer.alloc(32,8),apiKey='test-engine-key',apiBase='https://engine.invalid/api/v1';
const contract=PINNED_REVIEWED_WRITEBACK_CONTRACT;
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(done=>{resolve=done;});return{promise,resolve};}
function engine(){const stored=new Map<string,Record<string,unknown>>(),calls:string[]=[];let pause:{entered:ReturnType<typeof deferred>;release:ReturnType<typeof deferred>}|null=null;const fetcher:typeof fetch=async(input,init)=>{const path=new URL(String(input)).pathname,key=new Headers(init?.headers).get('Idempotency-Key')!,body=JSON.parse(String(init?.body)) as Record<string,unknown>;calls.push(key);const held=pause;pause=null;if(held){held.entered.resolve();await held.release.promise;}let response=stored.get(key);
  if(!response){if(path.endsWith('/hypotheses'))response={id:randomUUID(),statement:body.statement,context:body.context,status:'draft',confidence:null,initial_confidence:null,created_by:body.created_by,channel:body.channel,experimental_design:body.experimental_design,metadata:body.metadata,outcome:null,is_archived:false};
    else{const id=/hypotheses\/([a-f0-9-]+)\/evidence/.exec(path)![1]!,draft=[...stored.values()].find(v=>v.id===id)!;response={evidence:{id:randomUUID(),hypothesis_id:id,content:body.content,source:body.source,evidence_type:'neutral',created_by:body.created_by},hypothesis:{...draft,id,status:'draft',outcome:null}};}stored.set(key,response);}
  return new Response(JSON.stringify(response),{status:201});};return{fetcher,calls,pauseNext(){const entered=deferred(),release=deferred();pause={entered,release};return{entered:entered.promise,release:release.resolve};}};}
pgDescribe('project research delivery policy on isolated PostgreSQL',()=>{const db=`motive_policy_${randomUUID().replaceAll('-','')}`,operator=`operator:${randomUUID()}`,owner=`account:${randomUUID()}`,reviewer=`account:${randomUUID()}`,contributor=`account:${randomUUID()}`,contributor2=`account:${randomUUID()}`,contributor3=`account:${randomUUID()}`;
  let admin:Pool,pool:Pool,participation:ParticipationService,context:ParticipationAgentContext,context2:ParticipationAgentContext,context3:ParticipationAgentContext,projectId:string,workOrderId:string,scopeId:string,submissionId:string,submissionId2:string,submissionId3:string,reportDigest:string,reportDigest2:string,reportDigest3:string;
  const active=new Set([owner,reviewer,contributor,contributor2,contributor3]);const mock=engine();let service:ReturnType<typeof createProjectResearchDeliveryPolicyService>;
  async function waitForLock(queryFragment:string){for(let attempt=0;attempt<200;attempt++){const waiting=await admin.query(`SELECT 1 FROM pg_stat_activity WHERE datname=$1 AND state='active' AND wait_event_type='Lock' AND position($2 in query)>0`,[db,queryFragment]);if(waiting.rowCount)return;await new Promise<void>(resolve=>setImmediate(resolve));}throw new Error(`Expected blocked PostgreSQL statement was not observed: ${queryFragment}`);}
  beforeAll(async()=>{const source=new URL(baseUrl!),adminUrl=new URL(source);adminUrl.pathname='/postgres';admin=new Pool({connectionString:adminUrl.toString(),max:1});await admin.query(`CREATE DATABASE ${db}`);const url=new URL(source);url.pathname=`/${db}`;pool=new Pool({connectionString:url.toString(),max:2,application_name:'policy-authority-main'});await applyPostgresMigrations(pool);expect((await getPostgresSchemaStatus(pool)).exact).toBe(true);
    const project=await new LedgerKernel(pool).createProject({actorId:operator,idempotencyKey:randomUUID(),slug:'circle-packing',visibility:'PUBLIC',revisionContent:{title:'Policy test'}});projectId=project.id;
    await pool.query(`INSERT INTO motive.account_identities(actor_id,provider,subject_id,status,created_at) VALUES($1,'supabase',$2,'ACTIVE',clock_timestamp()),($3,'supabase',$4,'ACTIVE',clock_timestamp()),($5,'supabase',$6,'ACTIVE',clock_timestamp()),($7,'supabase',$8,'ACTIVE',clock_timestamp()),($9,'supabase',$10,'ACTIVE',clock_timestamp())`,[owner,owner.slice(8),reviewer,reviewer.slice(8),contributor,contributor.slice(8),contributor2,contributor2.slice(8),contributor3,contributor3.slice(8)]);
    await pool.query(`INSERT INTO motive.memberships(id,project_id,actor_id,role,scopes,granted_by) VALUES
      ($1,$2,$3,'OWNER',ARRAY['project:admin'],$6),($4,$2,$5,'STEWARD',ARRAY['project:admin'],$6)`,
    [randomUUID(),projectId,owner,randomUUID(),reviewer,operator]);
    participation=createParticipationService(pool,{tokenSecret:`test-${'s'.repeat(48)}`,issuerActorId:operator});workOrderId=(await participation.ensureCircleWorkOrder()).id;const joined=await participation.join(contributor,'Contributor',{projectSlug:'circle-packing',publishDisplayName:false,acceptReferenceTerms:true},'join-policy-test');context=await participation.authenticateBearer(joined.token);await participation.claimAssignment(context,workOrderId,'claim-policy-test');
    const submission=await participation.submitWitness(context,workOrderId,{leaseEpoch:1,witness:'{"format":"motive.csqv.witness.v1","n":101,"circles":[]}',investigation:{format:'motive.investigation.v1',proposal:'Test one bounded candidate.',expectation:'The protected checker evaluates it.',conditions:['Use the frozen checker.'],observations:['A candidate was checked.'],assessment:'Read the report before interpretation.',nextAction:'Choose a distinct bounded test.'}},'submit-policy-test');submissionId=submission.id;
    const artifact=await pool.query('SELECT report_digest FROM motive.participation_submission_artifacts WHERE submission_id=$1',[submissionId]);reportDigest=artifact.rows[0].report_digest;await participation.completeAssignment(context,workOrderId,{leaseEpoch:1,submissionId},'complete-policy-test');await participation.createPostCheckAssessment(context,submissionId,{reportDigest,assessment:'The candidate was rejected.',nextAction:'Try another bounded branch.'},'assess-policy-test');
    const joined2=await participation.join(contributor2,'Second contributor',{projectSlug:'circle-packing',publishDisplayName:false,acceptReferenceTerms:true},'join-policy-test-2');context2=await participation.authenticateBearer(joined2.token);const claim2=await participation.claimAssignment(context2,workOrderId,'claim-policy-test-2');if(claim2.leaseEpoch===null)throw new Error('External claim lease epoch is missing.');const leaseEpoch2=claim2.leaseEpoch;const submission2=await participation.submitWitness(context2,workOrderId,{leaseEpoch:leaseEpoch2,witness:'{"format":"motive.csqv.witness.v1","n":101,"circles":[]}',investigation:{format:'motive.investigation.v1',proposal:'Test a second bounded candidate.',expectation:'The protected checker evaluates it.',conditions:['Use the frozen checker.'],observations:['A second candidate was checked.'],assessment:'Read its report.',nextAction:'Compare distinct branches.'}},'submit-policy-test-2');submissionId2=submission2.id;const artifact2=await pool.query('SELECT report_digest FROM motive.participation_submission_artifacts WHERE submission_id=$1',[submissionId2]);reportDigest2=artifact2.rows[0].report_digest;await participation.completeAssignment(context2,workOrderId,{leaseEpoch:leaseEpoch2,submissionId:submissionId2},'complete-policy-test-2');await participation.createPostCheckAssessment(context2,submissionId2,{reportDigest:reportDigest2,assessment:'The second candidate was rejected.',nextAction:'Retain the comparison.'},'assess-policy-test-2');
    const joined3=await participation.join(contributor3,'Third contributor',{projectSlug:'circle-packing',publishDisplayName:false,acceptReferenceTerms:true},'join-policy-test-3');context3=await participation.authenticateBearer(joined3.token);const claim3=await participation.claimAssignment(context3,workOrderId,'claim-policy-test-3');if(claim3.leaseEpoch===null)throw new Error('External claim lease epoch is missing.');const leaseEpoch3=claim3.leaseEpoch;const submission3=await participation.submitWitness(context3,workOrderId,{leaseEpoch:leaseEpoch3,witness:'{"format":"motive.csqv.witness.v1","n":101,"circles":[]}',investigation:{format:'motive.investigation.v1',proposal:'Test a third bounded candidate.',expectation:'The protected checker evaluates it.',conditions:['Use the frozen checker.'],observations:['A third candidate was checked.'],assessment:'Read its report.',nextAction:'Retain the independent branch.'}},'submit-policy-test-3');submissionId3=submission3.id;const artifact3=await pool.query('SELECT report_digest FROM motive.participation_submission_artifacts WHERE submission_id=$1',[submissionId3]);reportDigest3=artifact3.rows[0].report_digest;await participation.completeAssignment(context3,workOrderId,{leaseEpoch:leaseEpoch3,submissionId:submissionId3},'complete-policy-test-3');await participation.createPostCheckAssessment(context3,submissionId3,{reportDigest:reportDigest3,assessment:'The third candidate was rejected.',nextAction:'Retain the comparison.'},'assess-policy-test-3');
    scopeId=randomUUID();await pool.query(`INSERT INTO motive.project_research_scopes(id,project_id,provider,api_base_url,tenant_id,channel_id,channel_name,channel_snapshot,channel_snapshot_digest,encrypted_api_key,credential_fingerprint,configuration_digest,api_version,inspected_source_revision,status,bound_by,verified_at) VALUES($1,$2,'hypothesis-engine',$3,$4,$5,'test','{}',$6,$7,$8,$9,'1.8.0',$10,'CONNECTED',$11,clock_timestamp())`,[scopeId,projectId,apiBase,randomUUID(),randomUUID(),`sha256:${'a'.repeat(64)}`,encryptSecret(vaultKey,apiKey,`research-scope:v1:${scopeId}:${projectId}`),`sha256:${'b'.repeat(64)}`,`sha256:${'c'.repeat(64)}`,'7'.repeat(40),owner]);
    service=createProjectResearchDeliveryPolicyService({pool,vaultKey,isActorActive:async a=>{await pool.query('SELECT 1');return active.has(a);},fetch:mock.fetcher,timeoutMs:1000});
  },30000);afterAll(async()=>{await pool?.end();if(admin){await admin.query('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1 AND pid<>pg_backend_pid()',[db]);await admin.query(`DROP DATABASE IF EXISTS ${db}`);await admin.end();}});
  it('requires explicit owner approval, retains one delivery, and advances at most one engine operation per call',async()=>{expect((await service.capability(context)).status).toBe('OWNER_APPROVAL_REQUIRED');const args={projectSlug:'circle-packing',scopeId,workOrderId,idempotencyKey:'approve-policy-test',approvedApiBaseUrl:apiBase,contract};
    await expect(service.approve(owner,{...args,idempotencyKey:'forged-contract-policy',
      contract:{...contract,implementationDigest:'f'.repeat(64)}},false)).rejects.toMatchObject({code:'VALIDATION'});
    const dry=await service.approve(owner,args,false);expect(dry).toMatchObject({status:'DRY_RUN',projectRevision:1});expect(Number.isFinite(dry.projectRevision)).toBe(true);
    const concurrentArgs={...args,idempotencyKey:'concurrent-policy-approval'};const concurrent=await Promise.all([service.approve(owner,concurrentArgs,true),service.approve(owner,concurrentArgs,true)]);expect(new Set(concurrent.map(item=>item.id)).size).toBe(1);
    const policy=await service.approve(owner,args,true);expect(policy.status).toBe('ACTIVE');expect((await service.capability(context)).policyId).toBe(policy.id);
    const ownerSender=createHypothesisSubmissionDeliveryService({pool,vaultKey,isActorActive:async a=>{await pool.query('SELECT 1');return active.has(a);},fetch:mock.fetcher,timeoutMs:1000});
    const ownerPrepared=await ownerSender.sync(owner,{projectSlug:'circle-packing',scopeId,submissionId,idempotencyKey:'owner-prepared-delivery',approvedApiBaseUrl:apiBase,contract,execute:false});
    expect(ownerPrepared).toMatchObject({status:'PENDING',pendingOperation:'DRAFT_HYPOTHESIS'});
    const admission=createHypothesisSubmissionAdmissionService({pool,vaultKey,isActorActive:async a=>{await pool.query('SELECT 1');return active.has(a);},sender:ownerSender});
    const admit=async(id:string,key:string)=>{const callsBefore=mock.calls.length;const preview=await admission.prepareAdmissionPreview(reviewer,id);
      expect(mock.calls).toHaveLength(callsBefore);await admission.decideAdmission(reviewer,id,{packageDigest:preview.packageDigest,
        expectedDecisionId:preview.latestDecision?.id??null,decision:'ADMIT',rationale:'Independent review admits this exact checked result as neutral research context.'},key);};
    await admit(submissionId,'admit-policy-submission-1');
    const first=await service.syncFromAgent(context,submissionId,{policyId:policy.id,reportDigest},'sync-policy-test');expect(first).toMatchObject({status:'DRAFT_RECORDED',reason:'NEXT_OPERATION_REQUIRES_RETRY'});expect(mock.calls).toHaveLength(1);const second=await service.syncFromAgent(context,submissionId,{policyId:policy.id,reportDigest},'sync-policy-test');expect(second.status).toBe('EVIDENCE_RECORDED');expect(mock.calls).toHaveLength(2);
    expect(second.sourceIntentId).toBe(ownerPrepared.sourceIntentId);const counts=await pool.query(`SELECT (SELECT count(*) FROM motive.hypothesis_submission_deliveries WHERE source_submission_id=$1) deliveries,(SELECT count(*) FROM motive.agent_research_sync_requests WHERE submission_id=$1) requests,(SELECT created_by_actor_id FROM motive.hypothesis_submission_deliveries WHERE source_submission_id=$1) creator`,[submissionId]);expect(Number(counts.rows[0].deliveries)).toBe(1);expect(Number(counts.rows[0].requests)).toBe(1);expect(counts.rows[0].creator).toBe(owner);
    const alternate=await service.approve(owner,{...args,idempotencyKey:'approve-alternate-policy'},true);const callsBeforeReplay=mock.calls.length;
    await admit(submissionId2,'admit-policy-submission-2');
    const [replay,otherCredential]=await Promise.all([service.syncFromAgent(context,submissionId,{policyId:alternate.id,reportDigest},'alternate-policy-sync'),service.syncFromAgent(context2,submissionId2,{policyId:policy.id,reportDigest:reportDigest2},'sync-policy-test')]);expect(replay).toMatchObject({status:'EVIDENCE_RECORDED',sourceIntentId:ownerPrepared.sourceIntentId});expect(otherCredential).toMatchObject({status:'DRAFT_RECORDED',reason:'NEXT_OPERATION_REQUIRES_RETRY'});expect(mock.calls).toHaveLength(callsBeforeReplay+1);
    const afterReplay=await pool.query('SELECT count(*) AS count,min(created_by_actor_id) AS creator FROM motive.hypothesis_submission_deliveries WHERE source_submission_id=$1',[submissionId]);expect(Number(afterReplay.rows[0].count)).toBe(1);expect(afterReplay.rows[0].creator).toBe(owner);
    const mappedKeys=await pool.query(`SELECT request.id,request.agent_token_id,intent.idempotency_key FROM motive.agent_research_sync_requests request
      JOIN motive.hypothesis_writeback_intents intent ON intent.prepared_by_actor_id=('policy:'||request.policy_id::text)
        AND intent.source_submission_id=request.submission_id WHERE request.idempotency_key='sync-policy-test' ORDER BY request.agent_token_id`);
    expect(mappedKeys.rowCount).toBe(2);expect(new Set(mappedKeys.rows.map(row=>row.id)).size).toBe(2);expect(new Set(mappedKeys.rows.map(row=>row.idempotency_key)).size).toBe(2);
    const otherPolicy=await service.approve(owner,{...args,idempotencyKey:'approve-other-policy'},true);const callsBeforeOtherReplay=mock.calls.length;
    const otherReplay=await service.syncFromAgent(context,submissionId,{policyId:otherPolicy.id,reportDigest},'other-policy-sync');expect(otherReplay).toMatchObject({status:'EVIDENCE_RECORDED',sourceIntentId:ownerPrepared.sourceIntentId});expect(mock.calls).toHaveLength(callsBeforeOtherReplay);
    await admit(submissionId3,'admit-policy-submission-3');const paused=mock.pauseNext(),callsBeforeRace=mock.calls.length;const dispatch=service.syncFromAgent(context3,submissionId3,{policyId:alternate.id,reportDigest:reportDigest3},'policy-approver-race');void dispatch.catch(()=>undefined);let retirement:Promise<unknown>|null=null;
    try{await Promise.race([paused.entered,new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('Policy dispatch did not reach the paused engine.')),2000))]);retirement=pool.query(`UPDATE motive.memberships SET revoked_at=clock_timestamp() /* policy-approver-membership-race */ WHERE project_id=$1 AND actor_id=$2`,[projectId,owner]);let retirementSettled=false;void retirement.then(()=>{retirementSettled=true;},()=>{retirementSettled=true;});await waitForLock('policy-approver-membership-race');expect(retirementSettled).toBe(false);paused.release();await expect(dispatch).resolves.toMatchObject({status:'DRAFT_RECORDED',pendingOperation:'NEUTRAL_EVIDENCE'});await retirement;expect(mock.calls).toHaveLength(callsBeforeRace+1);await expect(service.syncFromAgent(context3,submissionId3,{policyId:alternate.id,reportDigest:reportDigest3},'policy-approver-retired')).rejects.toMatchObject({code:'FORBIDDEN'});expect(mock.calls).toHaveLength(callsBeforeRace+1);
      await pool.query(`UPDATE motive.memberships SET revoked_at=NULL WHERE project_id=$1 AND actor_id=$2`,[projectId,owner]);
    }finally{paused.release();await Promise.allSettled(retirement?[dispatch,retirement]:[dispatch]);await pool.query(`UPDATE motive.memberships SET revoked_at=NULL WHERE project_id=$1 AND actor_id=$2`,[projectId,owner]);}
    await expect(service.syncFromAgent(context,submissionId,{policyId:policy.id,reportDigest:`sha256:${'0'.repeat(64)}`},'sync-policy-test')).rejects.toMatchObject({code:'CONFLICT'});
    await expect(service.syncFromAgent(context,submissionId,{policyId:policy.id,reportDigest:`sha256:${'0'.repeat(64)}`},'wrong-report-key')).rejects.toMatchObject({code:'FORBIDDEN'});
    active.delete(owner);expect((await service.capability(context)).status).toBe('OWNER_APPROVAL_REQUIRED');await expect(service.syncFromAgent(context,submissionId,{policyId:policy.id,reportDigest},'stopped-approver-sync')).rejects.toMatchObject({code:'FORBIDDEN'});active.add(owner);
    await service.revoke(owner,{policyId:policy.id,idempotencyKey:'revoke-policy-test'},true);await expect(service.syncFromAgent(context,submissionId,{policyId:policy.id,reportDigest},'sync-after-revoke')).rejects.toMatchObject({code:'FORBIDDEN'});
    let callsBeforeDenial=mock.calls.length;await pool.query('UPDATE motive.participation_agent_tokens SET revoked_at=clock_timestamp() WHERE id=$1',[context2.tokenId]);await expect(service.syncFromAgent(context2,submissionId2,{policyId:alternate.id,reportDigest:reportDigest2},'revoked-token-sync')).rejects.toMatchObject({code:'UNAUTHORIZED'});expect(mock.calls).toHaveLength(callsBeforeDenial);
    callsBeforeDenial=mock.calls.length;await pool.query(`UPDATE motive.account_identities SET status='DELETION_PENDING',deletion_requested_at=clock_timestamp() WHERE actor_id=$1`,[contributor3]);await expect(service.syncFromAgent(context3,submissionId3,{policyId:alternate.id,reportDigest:reportDigest3},'inactive-account-sync')).rejects.toMatchObject({code:'UNAUTHORIZED'});expect(mock.calls).toHaveLength(callsBeforeDenial);
    const replacementScope=randomUUID(),replacementConfiguration=`sha256:${'4'.repeat(64)}`;await pool.query(`INSERT INTO motive.project_research_scopes(id,project_id,provider,api_base_url,tenant_id,channel_id,channel_name,channel_snapshot,channel_snapshot_digest,encrypted_api_key,credential_fingerprint,configuration_digest,api_version,inspected_source_revision,status,bound_by,verified_at) VALUES($1,$2,'hypothesis-engine',$3,$4,$5,'replacement','{}',$6,$7,$8,$9,'1.8.0',$10,'REPLACEMENT_PENDING',$11,clock_timestamp())`,[replacementScope,projectId,apiBase,randomUUID(),randomUUID(),`sha256:${'5'.repeat(64)}`,encryptSecret(vaultKey,apiKey,`research-scope:v1:${replacementScope}:${projectId}`),`sha256:${'6'.repeat(64)}`,replacementConfiguration,'8'.repeat(40),owner]);await pool.query(`UPDATE motive.project_research_scopes SET status='REPLACED',replaced_at=clock_timestamp(),replaced_by=$2 WHERE id=$1`,[scopeId,replacementScope]);
    callsBeforeDenial=mock.calls.length;await expect(service.syncFromAgent(context,submissionId,{policyId:alternate.id,reportDigest},'replaced-scope-sync')).rejects.toMatchObject({code:'FORBIDDEN'});expect(mock.calls).toHaveLength(callsBeforeDenial);await pool.query(`UPDATE motive.project_research_scopes SET status='CONNECTED' WHERE id=$1`,[replacementScope]);
    const replacementPolicy=await service.approve(owner,{...args,scopeId:replacementScope,idempotencyKey:'replacement-scope-policy'},true);await pool.query(`INSERT INTO motive.project_revisions(id,project_id,revision,format,content,content_digest,created_by) SELECT $2,project_id,2,format,content,content_digest,$3 FROM motive.project_revisions WHERE project_id=$1 AND revision=1`,[projectId,randomUUID(),owner]);await pool.query('UPDATE motive.projects SET current_revision=2 WHERE id=$1',[projectId]);
    callsBeforeDenial=mock.calls.length;await expect(service.syncFromAgent(context,submissionId,{policyId:replacementPolicy.id,reportDigest},'stale-work-revision-sync')).rejects.toMatchObject({code:'FORBIDDEN'});expect(mock.calls).toHaveLength(callsBeforeDenial);
  });
});
